
OWNER_ID = 5022129097 

BLOCKED_SENDER_IDS = []

OLLAMA_URL = "http://localhost:11434/api/chat"

OLLAMA_MODEL = "girl"

HISTORY_LIMIT = 12

BUFFER_DELAY = 4

PARAGRAPH_DELAY = 3

IDLE_HOURS_BEFORE_SLEEP = 4

IDLE_CHECK_INTERVAL_SECONDS = 900

DIARY_COMPRESS_THRESHOLD = 20

DIARY_KEEP_RECENT = 5

MONITORED_CHANNELS = ["jolybells", "IgorLinkChannel", "welcome2RHK"]

PROACTIVE_TARGET_ID = OWNER_ID

PROACTIVE_CHECK_INTERVAL_SECONDS = 3600
PROACTIVE_JITTER_SECONDS = 600

PROACTIVE_SHARE_CHANCE = 0.30

PROACTIVE_MESSAGES_PER_CHANNEL = 20

HEARTBEAT_INTERVAL_SECONDS = 3600

SHORT_DELAY_RANGE = (2, 12)

LONG_DELAY_RANGE = (60, 180)
 
LONG_DELAY_CHANCE = 0.05

PROACTIVE_CHECKIN_MIN_EXCHANGES = 5

PROACTIVE_CHECKIN_HOURS = 2

RECALL_MAX_RESULTS = 3

RECALL_CONTEXT_PADDING = 1

WEB_SEARCH_ENABLED = False

DIARY_ENABLED = True

PROACTIVE_ENABLED = False

VISION_ENABLED = True

MOOD_ENABLED = True

FILES_ENABLED = False

LONG_TERM_MEMORY_ENABLED = False


CURIOSITY_ENABLED = True
CURIOSITY_CHECK_INTERVAL_SECONDS = 3600
CURIOSITY_JITTER_SECONDS = 600
CURIOSITY_CHANCE = 0.20

PROACTIVE_CHECKIN_ENABLED = True

QA_ENABLED = True
QA_CONTEXT_MESSAGES = 6